module.exports.descriptors = [
  "meaning decorated",
  "meaning special",
  "meaning unique as well as a reference to the goddess Parvati",
  "meaning self-confident",
  "meaning rich",
  "meaning desire or greatness",
  "meaning stability or from the Earth",
  "meaning shining",
  "meaning divine",
  "also meaning divine",
  "meaning cheerful",
  "meaning dewdrops",
  "meaning miracle",
  "meaning young",
  "meaning captivating",
  "meaning first ray of the sun",
  "meaning univers",
  "meaning star.",
];

module.exports.titles = [
  "Adah",
  "Anaisha",
  "Ananya",
  "Asmee",
  "Ishana",
  "Ishita",
  "kaia",
  "Kashvi",
  "Kimaya",
  "Krisha",
  "larisa",
  "Mahika",
  "Mirai",
  "Navya",
  "Rebecca",
  "Shanaya",
  "Shrishti",
  "Taara",
];
